apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-analysis-[K8S_AREA_ID]
  labels:
    app: event-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-analysis
      area: [K8S_AREA_ID]
  template:
    metadata:
      labels:
        app: event-analysis
        area: [K8S_AREA_ID]
    spec:
      serviceAccountName: event-management-sa
      containers:
      - name: analysis
        image: event-analysis:latest
        imagePullPolicy: Never
        env:
        - name: AREA_ID
          value: "[AREA_ID]"
        - name: MQTT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: EVENTANALYSIS_PROBE_THRESHOLD_RSSI
          valueFrom:
            configMapKeyRef:
              name: event-analysis-config
              key: EVENTANALYSIS_PROBE_THRESHOLD_RSSI
              optional: true
        - name: EVENTANALYSIS_ANALYSIS_WINDOWS_SIZE
          valueFrom:
            configMapKeyRef:
              name: event-analysis-config
              key: EVENTANALYSIS_ANALYSIS_WINDOWS_SIZE
              optional: true
        - name: EVENTANALYSIS_ANALYSIS_MEAN_EXP_INT
          valueFrom:
            configMapKeyRef:
              name: event-analysis-config
              key: EVENTANALYSIS_ANALYSIS_MEAN
              optional: true
        - name: EVENTANALYSIS_ANALYSIS_TREND_HIGHLY_ANGLE
          valueFrom:
            configMapKeyRef:
              name: event-analysis-config
              key: EVENTANALYSIS_ANALYSIS_TREND_HIGHLY_ANGLE
              optional: true
        - name: EVENTANALYSIS_ANALYSIS_TREND_MAX_STABLE_ANGLE
          valueFrom:
            configMapKeyRef:
              name: event-analysis-config
              key: EVENTANALYSIS_ANALYSIS_TREND_MAX_STABLE_ANGLE
              optional: true